baseURL = "https://caefis.netlify.app/"
canonifyURLs = false
disableAliases = true
disableHugoGeneratorInject = true
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
languageCode = "es-ES"
paginate = 7
rssLimit = 15
disablePathToLower = true

# redirects/headers
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS", "ALGOLIA"]
section = ["HTML", "RSS", "SITEMAP"]

# remover .{ext} de text/netlify
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

# formato de netlify _redirects
[outputFormats.REDIRECTS]
mediaType = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# formato de netlify _headers
[outputFormats.HEADERS]
mediaType = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

# Formato del output para sección sitemap.xml
[outputFormats.SITEMAP]
mediaType = "application/xml"
baseName = "sitemap"
isHTML = false
isPlainText = true
noUgly = true
rel  = "sitemap"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]

[caches]
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "10s"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[taxonomies]
  contributor = "contributors"
  type = "types"
  functionality = "functionalities"
  tag = "tags"

[permalinks]
  blog = "/blog/:title/"
  types = "/experimental/types/:title/"
  functionalities = "/experimental/functionalities/:title/"

[minify.tdewolff.html]
  keepWhitespace = false

[module]
  [module.hugoVersion]
    extended = true
    min = "0.80.0"
    max = ""
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "node_modules/flexsearch"
    target = "assets/js/vendor/flexsearch"
  [[module.mounts]]
    source = "node_modules/katex"
    target = "assets/js/vendor/katex"
  [[module.mounts]]
    source = "node_modules/mermaid"
    target = "assets/js/vendor/mermaid"
