[[pregrado]]
name = "Semestre"
weight = 10
identifier = "semestre"
url = "/semestre/"

[[pregrado]]
name = "Adicional"
weight = 20
identifier = "cursos"
url = "/cursos/"

[[posgrado]]
name = "Research"
weight = 10
identifier = "research"
url = "/research/"

[[main]]
  name = "San Marcos"
  url = "/pregrado/"
  weight = 10

[[main]]
  name = "Biblioteca"
  url = "/biblioteca/"
  weight = 20

[[main]]
  name = "Experimental"
  url = "/experimental/"
  weight = 30

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 40

[[main]]
  name = "Pregrado"
  weight = 10
  url = "/pregrado/"
  parent = "San Marcos"

[[main]]
  name = "Posgrado"
  weight = 20
  url = "/posgrado/maestria"
  parent = "San Marcos"

[[social]]
  name = "Facebook"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" width=\"20\" height=\"20\" stroke=\"currentColor\" stroke-width=\"2\" fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"css-i6dzq1\"><path d=\"M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z\"></path></svg>"
  url = "https://www.facebook.com/Centro-de-Apoyo-Estudiantil-CAE-104949204450480"
  weight = 10

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/cae_fisica"
  weight = 20

[[social]]
  name = "Instagram"
  pre = "<svg viewBox=\"0 0 24 24\" width=\"20\" height=\"20\" stroke=\"currentColor\" stroke-width=\"2\" fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"css-i6dzq1\"><rect x=\"2\" y=\"2\" width=\"20\" height=\"20\" rx=\"5\" ry=\"5\"></rect><path d=\"M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z\"></path><line x1=\"17.5\" y1=\"6.5\" x2=\"17.51\" y2=\"6.5\"></line></svg>"
  url = "https://www.instagram.com/cae_fisica/"
  weight = 30

[[footer]]
  name = "Privacidad"
  url = "/privacidad"
  weight = 20

[[experimental]]
  name = "General"
  weight = 10
  identifier = "experimental"
  url = "/experimental/"

[[tertiary]]
  name = "Enviar un artículo o página web"
  url = "https://github.com/caefis/caefis.github.io/labels/sugerencia"
  weight = 10
