# Meta Data for SEO

## Homepage
title = "CAE"
titleSeparator = "-"
titleAddition = "Centro de Apoyo Estudiantil"
description = "Facilitando recursos para el estudio de la física."

## Open Graph
images = ["doks.png"]
ogLocale = "en_US"
domainTLD = "caefis.netlify.app"
titleHome = "CAE Theme"

## Twitter Cards
twitterSite = "@cae_fisica"
twitterCreator = "@totallynotdavid"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "CAE"
schemaAuthor = "David"
schemaAuthorTwitter = "https://twitter.com/totallynotdavid"
schemaAuthorLinkedIn = ""
schemaAuthorGitHub = "https://github.com/totallynotdavid"
schemaLocale = "en-US"
schemaLogo = "logo-doks.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "doks.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/cae_fisica"
schemaLinkedIn = ""
schemaGitHub = ""
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "360"

# Footer
footer = "Un proyecto del Centro de Apoyo Estudiantil"

# Feed
copyRight = "Copyright (c) 2022 — CAE"


# Alert
alert = false
alertDismissable = false
# alertText = ""
# alertText = ""
alertText = ""

# Edit Page
docsRepo = "https://github.com/caefis/caefis.github.io"
editPage = true

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  darkMode = true
  bootStrapJs = true
  highLight = true
  multilingualMode = false #
  docsVersioning = false #

[menu]
  [menu.section]
    auto = false
    collapsibleSidebar = true
